// <auto-generated />
using System;
using AuxiAPI.src.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuxiAPI.WebApi.Migrations
{
    [DbContext(typeof(CondominiosDbContext))]
    [Migration("20260708164048_CreateCacheTable")]
    partial class CreateCacheTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuxiAPI.src.Entities.CacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChaveCache")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("chave_cache");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("entidade_id");

                    b.Property<DateTime>("ExpiradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirado_em");

                    b.Property<DateTime?>("InvalidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidado_em");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_http");

                    b.Property<string>("MotivoInvalidacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo_invalidacao");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resposta");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_consulta");

                    b.Property<string>("UrlDaConsulta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url_da_consulta");

                    b.HasKey("Id");

                    b.HasIndex("ChaveCache");

                    b.HasIndex("TipoConsulta");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.HasIndex("ChaveCache", "ExpiradoEm", "InvalidadoEm");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("AuxiAPI.src.Entities.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BairroDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairroDoEndereco");

                    b.Property<string>("CEPDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cepDoEndereco");

                    b.Property<string>("CNPJDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpjDoCondominio");

                    b.Property<string>("CidadeDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidadeDoEndereco");

                    b.Property<string>("CodigoDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigoDoCondominio");

                    b.Property<string>("DataFinal_Administracao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataFinal_Administracao");

                    b.Property<string>("DataInicial_Administracao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataInicial_Administracao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("EstadoDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estadoDoEndereco");

                    b.Property<string>("NomeDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeDoCondominio");

                    b.Property<string>("NomeGerenteDeContas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeGerenteDeContas");

                    b.Property<string>("NomeSindico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeSindico");

                    b.Property<int>("NumeroDeTorres")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDeTorres");

                    b.Property<int>("NumeroDeUnidades")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDeUnidades");

                    b.Property<string>("NumeroDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numeroDoEndereco");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("condominios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BairroDoEndereco = "Auxiliadora",
                            CEPDoEndereco = "98567213",
                            CNPJDoCondominio = "12345678000101",
                            CidadeDoEndereco = "Porto Alegre",
                            CodigoDoCondominio = "0001",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "20/08/2021",
                            Endereco = "Rua do Cambraia",
                            EstadoDoEndereco = "RS",
                            NomeDoCondominio = "Residencial Brasil-Hexa",
                            NomeGerenteDeContas = "Antonio Banderas",
                            NomeSindico = "Alfonso Herrera",
                            NumeroDeTorres = 3,
                            NumeroDeUnidades = 90,
                            NumeroDoEndereco = "5010",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            BairroDoEndereco = "Tristeza",
                            CEPDoEndereco = "91183730",
                            CNPJDoCondominio = "12543867000101",
                            CidadeDoEndereco = "Porto Alegre",
                            CodigoDoCondominio = "0002",
                            DataFinal_Administracao = "01/06/2026",
                            DataInicial_Administracao = "10/04/2019",
                            Endereco = "Rua do Marcel",
                            EstadoDoEndereco = "RS",
                            NomeDoCondominio = "Residencial Vivendas do Pelé",
                            NomeGerenteDeContas = "Christopher Uckermann",
                            NomeSindico = "Lucio Flavio",
                            NumeroDeTorres = 2,
                            NumeroDeUnidades = 60,
                            NumeroDoEndereco = "103",
                            Status = "Inativo"
                        },
                        new
                        {
                            Id = 3,
                            BairroDoEndereco = "Moinhos de Vento",
                            CEPDoEndereco = "90450200",
                            CNPJDoCondominio = "98765432000110",
                            CidadeDoEndereco = "Porto Alegre",
                            CodigoDoCondominio = "0003",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "15/01/2023",
                            Endereco = "Avenida das Orquídeas",
                            EstadoDoEndereco = "RS",
                            NomeDoCondominio = "Residencial Jardim das Flores",
                            NomeGerenteDeContas = "Mariana Santos",
                            NomeSindico = "Pedro Almeida",
                            NumeroDeTorres = 4,
                            NumeroDeUnidades = 120,
                            NumeroDoEndereco = "1200",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 4,
                            BairroDoEndereco = "Centro",
                            CEPDoEndereco = "92700120",
                            CNPJDoCondominio = "11223344000155",
                            CidadeDoEndereco = "Canoas",
                            CodigoDoCondominio = "0004",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "05/09/2020",
                            Endereco = "Rua das Acácias",
                            EstadoDoEndereco = "RS",
                            NomeDoCondominio = "Condomínio Bela Vista",
                            NomeGerenteDeContas = "Yur Teixeira",
                            NomeSindico = "Clara Mendes",
                            NumeroDeTorres = 2,
                            NumeroDeUnidades = 48,
                            NumeroDoEndereco = "250",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 5,
                            BairroDoEndereco = "Santo Antônio",
                            CEPDoEndereco = "93010300",
                            CNPJDoCondominio = "55667788000199",
                            CidadeDoEndereco = "São Leopoldo",
                            CodigoDoCondominio = "0005",
                            DataFinal_Administracao = "20/02/2024",
                            DataInicial_Administracao = "22/11/2018",
                            Endereco = "Rua dos Eucaliptos",
                            EstadoDoEndereco = "RS",
                            NomeDoCondominio = "Parque dos Pinheiros",
                            NomeGerenteDeContas = "Juliana Pereira",
                            NomeSindico = "Sharon Garcia",
                            NumeroDeTorres = 3,
                            NumeroDeUnidades = 72,
                            NumeroDoEndereco = "89",
                            Status = "Inativo"
                        },
                        new
                        {
                            Id = 6,
                            BairroDoEndereco = "Jardins",
                            CEPDoEndereco = "01234567",
                            CNPJDoCondominio = "22111333000166",
                            CidadeDoEndereco = "São Paulo",
                            CodigoDoCondominio = "0006",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "01/03/2022",
                            Endereco = "Avenida do Sol",
                            EstadoDoEndereco = "SP",
                            NomeDoCondominio = "Condomínio Plaza Colucci",
                            NomeGerenteDeContas = "Mia Colucci",
                            NomeSindico = "Miguel Arango",
                            NumeroDeTorres = 5,
                            NumeroDeUnidades = 180,
                            NumeroDoEndereco = "144",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 7,
                            BairroDoEndereco = "Barra da Tijuca",
                            CEPDoEndereco = "22345678",
                            CNPJDoCondominio = "33222444000177",
                            CidadeDoEndereco = "Rio de Janeiro",
                            CodigoDoCondominio = "0007",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "10/06/2023",
                            Endereco = "Rua da Harmonia",
                            EstadoDoEndereco = "RJ",
                            NomeDoCondominio = "Residencial RBD",
                            NomeGerenteDeContas = "Roberta Pardo",
                            NomeSindico = "Diego Bustamante",
                            NumeroDeTorres = 4,
                            NumeroDeUnidades = 120,
                            NumeroDoEndereco = "200",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 8,
                            BairroDoEndereco = "Savassi",
                            CEPDoEndereco = "30456789",
                            CNPJDoCondominio = "44333555000188",
                            CidadeDoEndereco = "Belo Horizonte",
                            CodigoDoCondominio = "0008",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "15/09/2021",
                            Endereco = "Travessa das Estrelas",
                            EstadoDoEndereco = "MG",
                            NomeDoCondominio = "Parque Celina",
                            NomeGerenteDeContas = "Celina Ferrer",
                            NomeSindico = "Lupita Fernández",
                            NumeroDeTorres = 3,
                            NumeroDeUnidades = 90,
                            NumeroDoEndereco = "77",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 9,
                            BairroDoEndereco = "Meireles",
                            CEPDoEndereco = "60123456",
                            CNPJDoCondominio = "55444666000199",
                            CidadeDoEndereco = "Fortaleza",
                            CodigoDoCondominio = "0009",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "20/02/2024",
                            Endereco = "Boulevard das Artes",
                            EstadoDoEndereco = "CE",
                            NomeDoCondominio = "Vista Altos",
                            NomeGerenteDeContas = "Josy Luján",
                            NomeSindico = "Giovanni Méndez",
                            NumeroDeTorres = 6,
                            NumeroDeUnidades = 240,
                            NumeroDoEndereco = "310",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 10,
                            BairroDoEndereco = "Cambuí",
                            CEPDoEndereco = "13234567",
                            CNPJDoCondominio = "66555777000111",
                            CidadeDoEndereco = "Campinas",
                            CodigoDoCondominio = "0010",
                            DataFinal_Administracao = "",
                            DataInicial_Administracao = "05/11/2022",
                            Endereco = "Rua dos Sonhos",
                            EstadoDoEndereco = "SP",
                            NomeDoCondominio = "Condomínio Esperança",
                            NomeGerenteDeContas = "Victoria Díaz",
                            NomeSindico = "Lupita Fernández",
                            NumeroDeTorres = 2,
                            NumeroDeUnidades = 64,
                            NumeroDoEndereco = "510",
                            Status = "Ativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
