// <auto-generated />
using System;
using AuxiAPI.src.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuxiAPI.WebApi.Migrations
{
    [DbContext(typeof(CondominiosDbContext))]
    [Migration("20260709133443_AddCacheInvalidationTrigger")]
    partial class AddCacheInvalidationTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuxiAPI.src.Entities.CacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChaveCache")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("chave_cache");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("entidade_id");

                    b.Property<DateTime>("ExpiradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirado_em");

                    b.Property<DateTime?>("InvalidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidado_em");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_http");

                    b.Property<string>("MotivoInvalidacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo_invalidacao");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resposta");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_consulta");

                    b.Property<string>("UrlDaConsulta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url_da_consulta");

                    b.HasKey("Id");

                    b.HasIndex("ChaveCache");

                    b.HasIndex("TipoConsulta");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.HasIndex("ChaveCache", "ExpiradoEm", "InvalidadoEm");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("AuxiAPI.src.Entities.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BairroDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairroDoEndereco");

                    b.Property<string>("CEPDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cepDoEndereco");

                    b.Property<string>("CNPJDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpjDoCondominio");

                    b.Property<string>("CidadeDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidadeDoEndereco");

                    b.Property<string>("CodigoDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigoDoCondominio");

                    b.Property<string>("DataFinal_Administracao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataFinal_Administracao");

                    b.Property<string>("DataInicial_Administracao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataInicial_Administracao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("EstadoDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estadoDoEndereco");

                    b.Property<string>("NomeDoCondominio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeDoCondominio");

                    b.Property<string>("NomeGerenteDeContas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeGerenteDeContas");

                    b.Property<string>("NomeSindico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeSindico");

                    b.Property<int>("NumeroDeTorres")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDeTorres");

                    b.Property<int>("NumeroDeUnidades")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDeUnidades");

                    b.Property<string>("NumeroDoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numeroDoEndereco");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("condominios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
